name = "DrakanHex"
author = "alexyzer"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "445a7ddd9e7971e57358fc9871be9bf3e896b349541a2061f83904ef9da47b3e"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
