name = "DrakanHex"
author = "alexyzer"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af3aaacd1679cf9ed7f06485e3da6112d108ecec4897faa4e221ee45b5c8e2e2"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
